name: info_traffic_976
description: Une application d'info traffic pour le département de Mayotte
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cached_network_image: ^3.2.0
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_map: ^0.14.0
  http: ^0.13.4
  intl: any
  latlong2: ^0.8.1
  provider: ^6.0.2

dev_dependencies:
  bloc_test: any
  flutter_test:
    sdk: flutter
  mocktail: any
  very_good_analysis: any

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env